<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;
    public const TABLE = "products";

    protected $table = self::TABLE;
    protected $fillable = [
        "uuid",
        "sku_code",
        "title",
        "price",
        "details",
        "thumbnail",
        "original_image",
        "status",
        "created_by",
        "updated_by"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($query){
            $query->uuid       = Str::uuid()->toString();
            $query->created_by = userID();
            $query->thumbnail = 'we.jpg';
            $query->original_image = 'we.jpg';
        });

        static::updating(function($query){
            $query->updated_by = userID();
        });
    }

    /**
     * ############################
     * Relationship
     * ############################
     * */
    public function creator() : BelongsTo
    {
        return $this->belongsTo(User::class,"created_by");
    }

    public function updator() : BelongsTo
    {
        return $this->belongsTo(User::class,"updated_by");
    }

}
